config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :bookmarks
  resources :tipos
  patch '/bookmarks', to: 'bookmarks#update'
  post 'bookmarks/:id/add_category', to: 'bookmarks#add_category', as: 'add_category'
  post 'bookmarks/:id/add_subcategory', to: 'bookmarks#add_subcategory', as: 'add_subcategory'
  delete 'bookmarks/:id/remove_category/:category_id', to: 'bookmarks#remove_category', as: 'remove_category'
  get 'subcategories', to: 'subcategories#index', as: 'all_subcategories'
  get 'subcategories/new', to: 'subcategories#new', as: 'new_subcategorie'
  post 'subcategories', to: 'subcategories#create', as: 'subcategories'
  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :tipo, dependent: :destroy 
  has_and_belongs_to_many :categories, dependent: :destroy
  has_many :subcategories, dependent: :destroy
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy, :add_category, :remove_category]

  def add_category 
    @category = Category.find(params[:category_id])
    if @bookmark.categories.include?(@category)
      redirect_to root_path, alert: 'la categoría ya está agregada'
    else 
      @bookmark.categories.push(@category)
      redirect_to root_path, notice: 'Se ha agregado la categoría'
    end
  end
 
  def remove_category
    @category = Category.find(params[:category_id])
    @bookmark.categories.delete(@category)
    redirect_to bookmarks_path, notice: 'categoría eliminado'
  end

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.all
    @categories = Category.all
    @tipos = Tipo.all
    
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    
    @bookmark = Bookmark.find(params[:id])
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
    @tipos = Tipo.all
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:url, :tipo_id)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: [@tipo, bookmark], remote: true, data: { confirm: 'Are you sure?'} ) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.select :tipo_id, @tipos.map{|tipo| [tipo.name, tipo.id] }, selected: 0, prompt: "Seleccione una opción.." %>
  </div>
  
  <div class="actions">
    <%= form.submit 'Enviar', data: {disable_with: 'Enviando...'} %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= form_with(url: bookmarks_path, model:  @bookmark, remote: true, data: { confirm: 'Are you sure?'} ) do |form| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>



  <div class="actions">
    <%= form.submit 'Enviar', data: {disable_with: 'Enviando...'} %>
  </div>
<% end %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>


<%= render 'form', bookmark: @bookmark %>

<h1>Bookmarks</h1>
<div class="justify-content">
    <%= pie_chart Bookmark.group(:tipo).count, download: {background: "#ffffff"}, title: "Tipos de marcadores"%>
</div>
<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Tipo</th>
      <th>Categorias</th>
      <th>Subcategorias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.tipo.name %></td>
        
        <%= form_with(url: add_category_path(bookmark.id), method: :post) do |f|%>
        <% @filtered_categories = @categories.reject{|category| bookmark.categories.include?(category)}%>
        <td>
          <%= f.select :category_id, options_from_collection_for_select(@filtered_categories, :id, :name), selected: 0, prompt: 'Categoría'%>
          <%= f.submit 'Agregar'%>
        </td>
          <%end%>
        <% bookmark.categories.each do |category| %>
          <td><%= category.name%> <%= link_to ' X ', remove_category_path(bookmark.id, category.id), method: :delete%></td>
        <%end%>
        <% bookmark.subcategories.each do |subcategory| %>
          <td><%= subcategory.name%> </td>
        <%end%>
        
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %> <br>
<%= link_to 'Nueva subcategoría', new_subcategorie_path%>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @bookmark.tipo.name %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>