config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :bookmarks
  resources :tipos
  patch '/bookmarks', to: 'bookmarks#update'
  post 'bookmarks/:id/add_category', to: 'bookmarks#add_category', as: 'add_category'
  post 'bookmarks/:id/add_subcategory', to: 'bookmarks#add_subcategory', as: 'add_subcategory'
  delete 'bookmarks/:id/remove_category/:category_id', to: 'bookmarks#remove_category', as: 'remove_category'
  get 'subcategories', to: 'subcategories#index', as: 'all_subcategories'
  get 'subcategories/new', to: 'subcategories#new', as: 'new_subcategorie'
  post 'subcategories', to: 'subcategories#create', as: 'subcategories'
  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :bookmarks, dependent: :destroy
    has_many :subcategories, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
   
    respond_to do |format|
      format.html { render :show }
      format.json { render :show}
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td></td>
        <td id="vacio"><%= link_to category.name, category, :class => "btn btn-outline-dark " %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'privada', :class => "privada"%></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoría', new_category_path %> <br>
<%= link_to 'Nuevo Bookmark', new_bookmark_path %> <br>
<%= link_to 'Bookmarks', bookmarks_path %> <br>
<%= link_to 'Tipos', tipos_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h3>
  Categoría: <br>
 <strong> <%= @category.name %> </strong>
</h3>
<% if @category.subcategories != nil %>
    <% @category.subcategories.each do |subcat| %>
    Subcategoría: <br>
    <h4><%= subcat.name %></h4>
   <table id="table">
    <thead>
      <tr>
        <th>Marcadores</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @category.bookmarks.each do |bookmark| %>
        <tr>
          <td><ul><li><%= bookmark.url %> </li></ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <%end%>
<%else%>
<table>
  <thead>
    <tr>
      <th>Marcadores</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @category.bookmarks.each do |bookmark| %>
      <tr>
        <td><ul><li><%= bookmark.url %> </li></ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
   
<%end%>

<br>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>